language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=facebook_sdk

after_success:
  - coveralls
